apiVersion: v1
kind: Service
metadata:
  labels:
    app: curtail
  name: curtail
    #namespace: {{ .Release.Namespace | indent 4 }}
    #namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: curtail
status:
  loadBalancer: {}
