apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: curtpullsecret
data:
  {{- define "imagePullSecret" }}
  {{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" (.Values.imageCredentials.username | b64dec) (.Values.imageCredentials.password | b64dec) | b64enc) | b64enc }}
  {{- end }}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
