apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: curtdb-secret
    #namespace: {{ .Release.Namespace | indent 4 }}
data:
  password: {{ .Values.dbsecret | indent 4 }}
    #url: {{ printf "postgres://postgres:%s@curtdb.jghostdemo:5432/curtail" (.Values.dbsecret | b64dec) | b64enc }}
  url: {{ printf "postgres://postgres:%s@curtdb.default:5432/curtail" (.Values.dbsecret | b64dec) | b64enc }}
