apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghost-updated
  name: ghost-updated
    #namespace: {{ .Release.Namespace | indent 4 }}
    #namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-updated
  strategy: {}
  template:
    metadata:
      labels:
        app: ghost-updated
    spec:
      containers:
      - image: {{ printf "%s.azurecr.io/ghost:%s" .Values.ghostreg .Values.ghostupdated | indent 10 }}
        #- image: {{ printf "ghostcurtailreg.azurecr.io/ghost:%s" .Values.ghostupdated | indent 10 }}
        #- image: {{ printf "%s/jghost:%s" .Values.registry .Values.buildtag | indent 10 }}
        #- image: ghostcurtailreg.azurecr.io/ghost:2.2.3
        imagePullPolicy: Always
        name: ghost-updated
        ports:
        - containerPort: 2368
      restartPolicy: Always
status: {}
