apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ghost-current
  name: ghost-current
    #namespace: {{ .Release.Namespace | indent 4 }}
    #namespace: default
    #namespace: "kghostdemo-$(Build.BuildId)"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-current
  strategy: {}
  template:
    metadata:
      labels:
        app: ghost-current
    spec:
      containers:
      - image: {{ printf "%s.azurecr.io/ghost:%s" .Values.ghostreg .Values.ghostcurrent | indent 10 }}
        name: ghost-current
        ports:
        - containerPort: 2369
      restartPolicy: Always
status: {}
