apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost-updated
  name: ghost-updated
    #namespace: {{ .Release.Namespace | indent 4 }}
    #namespace: default
spec:
  ports:
  - name: "2368"
    port: 2368
    targetPort: 2368
  selector:
    app: ghost-updated
status:
  loadBalancer: {}
