apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: svc-reader
  namespace: {{ printf "%s" .Values.kube.namespace | indent 10 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-svcs
  namespace: {{ printf "%s" .Values.kube.namespace | indent 10 }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ printf "%s" .Values.kube.namespace | indent 10 }}
roleRef:
  kind: Role
  name: svc-reader
  apiGroup: rbac.authorization.k8s.io
